import pycountry


_PY_COUNTRIES = [country.name for country in pycountry.countries]
_PY_COUNTRIES_EX_SWE = [country.name for country in pycountry.countries]
_PY_COUNTRIES_EX_SWE.remove("Sweden")


## OECD/DAC countries
## need to be normalized against pycountries list before use. The intention is here to show additional value with the nlp apporach - can group the countries to key recipient countries, which will give additional value.
## source: 'http://www.oecd.org/dac/financing-sustainable-development/development-finance-standards/DAC-List-of-ODA-Recipients-for-reporting-2020-flows.pdf'
_DAC_RECIPIENTS = {
    "Least Developed Countries": [
        "Afghanistan",
        "Angola",
        "Bangladesh",
        "Benin",
        "Bhutan",
        "Burkina Faso",
        "Burundi",
        "Cambodia",
        "Central African Republic",
        "Chad",
        "Comoros",
        "Democratic Republic of the Congo",
        "Djibouti",
        "Eritrea",
        "Ethiopia",
        "Gambia",
        "Guinea",
        "Guinea-Bissau",
        "Haiti",
        "Kiribati",
        "Lao People's Democratic Republic",
        "Lesotho",
        "Liberia",
        "Madagascar",
        "Malawi",
        "Mali",
        "Mauritania",
        "Mozambique",
        "Myanmar",
        "Nepal",
        "Niger",
        "Rwanda",
        "Sao Tome and Principe",
        "Senegal",
        "Sierra Leone",
        "Solomon Islands",
        "Somalia",
        "South Sudan",
        "Sudan",
        "Tanzania",
        "Timor-Leste",
        "Togo",
        "Tuvalu",
        "Uganda",
        "Vanuatu",
        "Yemen",
    ],
    "Other Low Income Countries": ["Democratic People's Republic of Korea", "Zimbabwe"],
    "Lower Middle Income Countries": [
        "Armenia",
        "Bolivia",
        "Cabo Verde",
        "Cameroon",
        "Congo",
        "Côte d'Ivoire",
        "Egypt",
        "El Salvador",
        "Eswatini",
        "Georgia",
        "Ghana",
        "Guatemala",
        "Honduras",
        "India",
        "Indonesia",
        "Jordan",
        "Kenya",
        "Kosovo",
        "Kyrgyzstan",
        "Micronesia",
        "Moldova",
        "Mongolia",
        "Morocco",
        "Nicaragua",
        "Nigeria",
        "Pakistan",
        "Papua New Guinea",
        "Philippines",
        "Sri Lanka",
        "Syrian Arab Republic",
        "Tajikistan",
        "Tokelau",
        "Tunisia",
        "Ukraine",
        "Uzbekistan",
        "Viet Nam",
        "West Bank and Gaza Strip",
        "South Sudan",
        "Sudan",
        "Tanzania",
        "Timor-Leste",
        "Togo",
        "Tuvalu",
        "Uganda",
        "Vanuatu",
        "Yemen",
    ],
    "Upper Middle Income Countries": [
        "Albania",
        "Algeria",
        "Antigua and Barbuda",
        "Argentina",
        "Azerbaijan",
        "Belarus",
        "Belize",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "China (People's Republic of)",
        "Colombia",
        "Costa Rica",
        "Cuba",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Equatorial Guinea",
        "Fiji",
        "Gabon",
        "Grenada",
        "Guyana",
        "Iran",
        "Iraq",
        "Jamaica",
        "Kazakhstan",
        "Lebanon",
        "Libya",
        "Malaysia",
        "Maldives",
        "Marshall Islands",
        "Mauritius",
        "Mexico",
        "Montenegro",
        "Montserrat",
        "Namibia",
        "Nauru",
        "Niue",
        "North Macedonia",
        "Palau",
        "Panama",
        "Paraguay",
        "Peru",
        "Saint Helena",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "Serbia",
        "South Africa",
        "Suriname",
        "Thailand",
        "Tonga",
        "Turkey",
        "Turkmenistan",
        "Venezuela",
        "Wallis and Futuna",
    ],
}

## donor countries to be labled in the parsing.
## list have been manualy adjusted to pycountry/ISO standards for country names. "European Union" have been excluded.
## source: http://www.oecd.org/dac/dacmembers.htm/members
_DAC_DONORS = [
    "Australia",
    "Austria",
    "Belgium",
    "Canada",
    "Czechia",
    "Denmark",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Japan",
    "Korea, Republic of",
    "Luxembourg",
    "Netherlands",
    "New Zealand",
    "Norway",
    "Poland",
    "Portugal",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "United Kingdom",
    "United States",
]

## lookup for UNregion from contry converter package and normalized based on pycountry nomenculture for country names.
_UN_REGION = {
    "Afghanistan": "Southern Asia",
    "Aland Islands": "Northern Europe",
    "Albania": "Southern Europe",
    "Algeria": "Northern Africa",
    "American Samoa": "Polynesia",
    "Andorra": "Southern Europe",
    "Angola": "Middle Africa",
    "Anguilla": "Caribbean",
    "Antarctica": "Antarctica",
    "Antigua and Barbuda": "Caribbean",
    "Argentina": "South America",
    "Armenia": "Western Asia",
    "Aruba": "Caribbean",
    "Australia": "Australia and New Zealand",
    "Austria": "Western Europe",
    "Azerbaijan": "Western Asia",
    "Bahamas": "Caribbean",
    "Bahrain": "Western Asia",
    "Bangladesh": "Southern Asia",
    "Barbados": "Caribbean",
    "Belarus": "Eastern Europe",
    "Belgium": "Western Europe",
    "Belize": "Central America",
    "Benin": "Western Africa",
    "Bermuda": "Northern America",
    "Bhutan": "Southern Asia",
    "Bolivia, Plurinational State of": "South America",
    "Bonaire, Saint Eustatius and Saba": "Caribbean",
    "Bosnia and Herzegovina": "Southern Europe",
    "Botswana": "Southern Africa",
    "Bouvet Island": "South America",
    "Brazil": "South America",
    "British Antarctic Territories": "nan",
    "British Indian Ocean Territory": "Eastern Africa",
    "Virgin Islands, British": "Caribbean",
    "Brunei Darussalam": "South-Eastern Asia",
    "Bulgaria": "Eastern Europe",
    "Burkina Faso": "Western Africa",
    "Burundi": "Eastern Africa",
    "Cabo Verde": "Western Africa",
    "Cambodia": "South-Eastern Asia",
    "Cameroon": "Middle Africa",
    "Canada": "Northern America",
    "Cayman Islands": "Caribbean",
    "Central African Republic": "Middle Africa",
    "Chad": "Middle Africa",
    "Channel Islands": "Northern Europe",
    "Chile": "South America",
    "China": "Eastern Asia",
    "Christmas Island": "Australia and New Zealand",
    "Cocos (Keeling) Islands": "Australia and New Zealand",
    "Colombia": "South America",
    "Comoros": "Eastern Africa",
    "Congo Republic": "Middle Africa",
    "Cook Islands": "Polynesia",
    "Costa Rica": "Central America",
    "Cote d'Ivoire": "Western Africa",
    "Croatia": "Southern Europe",
    "Cuba": "Caribbean",
    "Curacao": "Caribbean",
    "Cyprus": "Western Asia",
    "Czechia": "Eastern Europe",
    "Denmark": "Northern Europe",
    "Djibouti": "Eastern Africa",
    "Dominica": "Caribbean",
    "Dominican Republic": "Caribbean",
    "DR Congo": "Middle Africa",
    "Ecuador": "South America",
    "Egypt": "Northern Africa",
    "El Salvador": "Central America",
    "Equatorial Guinea": "Middle Africa",
    "Eritrea": "Eastern Africa",
    "Estonia": "Northern Europe",
    "Eswatini": "Southern Africa",
    "Ethiopia": "Eastern Africa",
    "Faeroe Islands": "Northern Europe",
    "Falkland Islands": "South America",
    "Fiji": "Melanesia",
    "Finland": "Northern Europe",
    "France": "Western Europe",
    "French Guiana": "South America",
    "French Polynesia": "Polynesia",
    "French Southern Territories": "Eastern Africa",
    "Gabon": "Middle Africa",
    "Gambia": "Western Africa",
    "Georgia": "Western Asia",
    "Germany": "Western Europe",
    "Ghana": "Western Africa",
    "Gibraltar": "Southern Europe",
    "Greece": "Southern Europe",
    "Greenland": "Northern America",
    "Grenada": "Caribbean",
    "Guadeloupe": "Caribbean",
    "Guam": "Micronesia",
    "Guatemala": "Central America",
    "Guernsey": "Northern Europe",
    "Guinea": "Western Africa",
    "Guinea-Bissau": "Western Africa",
    "Guyana": "South America",
    "Haiti": "Caribbean",
    "Heard and McDonald Islands": "Australia and New Zealand",
    "Honduras": "Central America",
    "Hong Kong": "Eastern Asia",
    "Hungary": "Eastern Europe",
    "Iceland": "Northern Europe",
    "India": "Southern Asia",
    "Indonesia": "South-Eastern Asia",
    "Iran": "Southern Asia",
    "Iraq": "Western Asia",
    "Ireland": "Northern Europe",
    "Isle of Man": "Northern Europe",
    "Israel": "Western Asia",
    "Italy": "Southern Europe",
    "Jamaica": "Caribbean",
    "Japan": "Eastern Asia",
    "Jersey": "Northern Europe",
    "Jordan": "Western Asia",
    "Kazakhstan": "Central Asia",
    "Kenya": "Eastern Africa",
    "Kiribati": "Micronesia",
    "Kosovo": "Southern Europe",
    "Kuwait": "Western Asia",
    "Kyrgyzstan": "Central Asia",
    "Laos": "South-Eastern Asia",
    "Lao People's Democratic Republic": "South-Eastern Asia",
    "Latvia": "Northern Europe",
    "Lebanon": "Western Asia",
    "Lesotho": "Southern Africa",
    "Liberia": "Western Africa",
    "Libya": "Northern Africa",
    "Liechtenstein": "Western Europe",
    "Lithuania": "Northern Europe",
    "Luxembourg": "Western Europe",
    "Macao": "Eastern Asia",
    "Macedonia": "Southern Europe",
    "Madagascar": "Eastern Africa",
    "Malawi": "Eastern Africa",
    "Malaysia": "South-Eastern Asia",
    "Maldives": "Southern Asia",
    "Mali": "Western Africa",
    "Malta": "Southern Europe",
    "Marshall Islands": "Micronesia",
    "Martinique": "Caribbean",
    "Mauritania": "Western Africa",
    "Mauritius": "Eastern Africa",
    "Mayotte": "Eastern Africa",
    "Mexico": "Central America",
    "Micronesia, Fed. Sts.": "Micronesia",
    "Moldova, Republic of": "Eastern Europe",
    "Monaco": "Western Europe",
    "Mongolia": "Eastern Asia",
    "Montenegro": "Southern Europe",
    "Montserrat": "Caribbean",
    "Morocco": "Northern Africa",
    "Mozambique": "Eastern Africa",
    "Myanmar": "Eastern Asia",
    "Namibia": "Southern Africa",
    "Nauru": "Polynesia",
    "Nepal": "Southern Asia",
    "Netherlands": "Western Europe",
    "Netherlands Antilles": "nan",
    "New Caledonia": "Melanesia",
    "New Zealand": "Australia and New Zealand",
    "Nicaragua": "Central America",
    "Niger": "Western Africa",
    "Nigeria": "Western Africa",
    "Niue": "Polynesia",
    "Norfolk Island": "Australia and New Zealand",
    "North Korea": "Eastern Asia",
    "Northern Mariana Islands": "Micronesia",
    "Norway": "Northern Europe",
    "Oman": "Western Asia",
    "Pakistan": "Southern Asia",
    "Palau": "Micronesia",
    "Palestine": "Western Asia",
    "Panama": "Central America",
    "Papua New Guinea": "Melanesia",
    "Paraguay": "South America",
    "Peru": "South America",
    "Philippines": "South-Eastern Asia",
    "Pitcairn": "Polynesia",
    "Poland": "Eastern Europe",
    "Portugal": "Southern Europe",
    "Puerto Rico": "Caribbean",
    "Qatar": "Western Asia",
    "Reunion": "Eastern Africa",
    "Romania": "Eastern Europe",
    "Russia": "Eastern Europe",
    "Rwanda": "Eastern Africa",
    "Saint-Martin": "Caribbean",
    "Samoa": "Polynesia",
    "San Marino": "Southern Europe",
    "Sao Tome and Principe": "Middle Africa",
    "Saudi Arabia": "Western Asia",
    "Senegal": "Western Africa",
    "Serbia": "Southern Europe",
    "Seychelles": "Eastern Africa",
    "Sierra Leone": "Western Africa",
    "Singapore": "South-Eastern Asia",
    "Sint Maarten": "Caribbean",
    "Slovakia": "Eastern Europe",
    "Slovenia": "Southern Europe",
    "Solomon Islands": "Melanesia",
    "Somalia": "Eastern Africa",
    "South Africa": "Southern Africa",
    "South Georgia and South Sandwich Is.": "South America",
    "South Korea": "Eastern Asia",
    "South Sudan": "Eastern Africa",
    "Soviet Union (former)": "Eastern Europe",
    "Spain": "Southern Europe",
    "Sri Lanka": "Southern Asia",
    "St. Barths": "Caribbean",
    "St. Helena": "Western Africa",
    "St. Kitts and Nevis": "Caribbean",
    "St. Lucia": "Caribbean",
    "St. Pierre and Miquelon": "Northern America",
    "St. Vincent and the Grenadines": "Caribbean",
    "Sudan": "Northern Africa",
    "Suriname": "South America",
    "Svalbard and Jan Mayen Islands": "Northern Europe",
    "Sweden": "Northern Europe",
    "Switzerland": "Western Europe",
    "Syria": "Western Asia",
    "Taiwan, Province of China": "Eastern Asia",
    "Tajikistan": "Central Asia",
    "Tanganjika": "Eastern Africa",
    "Tanzania, United Republic of": "Eastern Africa",
    "Thailand": "South-Eastern Asia",
    "Timor-Leste": "South-Eastern Asia",
    "Togo": "Western Africa",
    "Tokelau": "Polynesia",
    "Tonga": "Polynesia",
    "Trinidad and Tobago": "Caribbean",
    "Tunisia": "Northern Africa",
    "Turkey": "Western Asia",
    "Turkmenistan": "Central Asia",
    "Turks and Caicos Islands": "Caribbean",
    "Tuvalu": "Polynesia",
    "Uganda": "Eastern Africa",
    "Ukraine": "Eastern Europe",
    "United Arab Emirates": "Western Asia",
    "United Kingdom": "Northern Europe",
    "United States": "Northern America",
    "United States Minor Outlying Islands": "Micronesia",
    "United States Virgin Islands": "Caribbean",
    "Uruguay": "South America",
    "Uzbekistan": "Central Asia",
    "Vanuatu": "Melanesia",
    "Vatican": "Southern Europe",
    "Venezuela, Bolivarian Republic of": "South America",
    "Viet Nam": "South-Eastern Asia",
    "Wallis and Futuna Islands": "Polynesia",
    "Western Sahara": "Northern Africa",
    "Yemen": "Western Asia",
    "Zambia": "Eastern Africa",
    "Zanzibar": "Eastern Africa",
    "Zimbabwe": "Eastern Africa",
}

